[tool.isort.settings]
known_third_party = ["django"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.3"
tag_format = "v$minor.$major.$patch$prerelease"

[tool.coverage.run]
branch = "True"
source = "backend"
omit = ["*/manage.py", "*/tests/*"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "backend.project.settings"
python_files = ["tests.py", "test_*.py" ,"*_tests.py"]