[tool.isort.settings]
known_third_party = ["django"]

[tool.commitizen]
name = "cz_conventional_commits"
<<<<<<< HEAD
version = "0.1.7"
=======
version = "1.0.13"
>>>>>>> 3afc94d0fd7972acf46d1a7b7ea65d345f4d7328
tag_format = "v$minor.$major.$patch$prerelease"

[tool.coverage.run]
branch = true
source = ["./src"]
omit = ["*/manage.py", "*/tests/*"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "src.config.settings"
python_files = ["tests.py", "test_*.py" ,"*_tests.py"]
