# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --skip-lock --dev
        pipenv lock --pre
        pipenv run pre-commit install --hook-type commit-msg
    - name: Lint with flake8
      run: pipenv run flake8 . --count --max-complexity=10 --max-line-length=127 --exclude=manage.py
    - name: pre-commit test run
      run: pipenv run pre-commit run --from-ref HEAD^ --to-ref HEAD
    - name: Test with pytest
      env: 
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        POSTGRES_USER: ${{secrets.POSTGRES_USER}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
        POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
      run: |
        pipenv run coverage run --source='./src' -m pytest --suppress-no-test-exit-code
